import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import ApplicationManager as AppManager

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(800, 634)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/heart-rate-monitor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_11 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setLineWidth(2)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Assets/medical.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.Solution_Volume_LCD = QtWidgets.QLCDNumber(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Solution_Volume_LCD.sizePolicy().hasHeightForWidth())
        self.Solution_Volume_LCD.setSizePolicy(sizePolicy)
        self.Solution_Volume_LCD.setMinimumSize(QtCore.QSize(170, 150))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Solution_Volume_LCD.setFont(font)
        self.Solution_Volume_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Solution_Volume_LCD.setStyleSheet("color: rgb(255, 255, 255);\n""")
        self.Solution_Volume_LCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Solution_Volume_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Solution_Volume_LCD.setSmallDecimalPoint(False)
        self.Solution_Volume_LCD.setDigitCount(4)
        self.Solution_Volume_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.Solution_Volume_LCD.setProperty("value", 0.0)
        self.Solution_Volume_LCD.setObjectName("Solution_Volume_LCD")
        self.gridLayout_4.addWidget(self.Solution_Volume_LCD, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setLineWidth(1)
        self.label_10.setScaledContents(True)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 2, 1, 1)
        self.Solution_Volume_Progress_Bar = QtWidgets.QProgressBar(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Solution_Volume_Progress_Bar.sizePolicy().hasHeightForWidth())
        self.Solution_Volume_Progress_Bar.setSizePolicy(sizePolicy)
        self.Solution_Volume_Progress_Bar.setMinimumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.Solution_Volume_Progress_Bar.setFont(font)
        self.Solution_Volume_Progress_Bar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Solution_Volume_Progress_Bar.setAutoFillBackground(False)
        self.Solution_Volume_Progress_Bar.setStyleSheet("")
        self.Solution_Volume_Progress_Bar.setProperty("value", 0)
        self.Solution_Volume_Progress_Bar.setTextVisible(True)
        self.Solution_Volume_Progress_Bar.setInvertedAppearance(False)
        self.Solution_Volume_Progress_Bar.setObjectName("Solution_Volume_Progress_Bar")
        self.gridLayout_4.addWidget(self.Solution_Volume_Progress_Bar, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setLineWidth(2)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Assets/blood-pressure.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.Heart_Rate_LCD = QtWidgets.QLCDNumber(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Heart_Rate_LCD.sizePolicy().hasHeightForWidth())
        self.Heart_Rate_LCD.setSizePolicy(sizePolicy)
        self.Heart_Rate_LCD.setMinimumSize(QtCore.QSize(170, 150))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Heart_Rate_LCD.setFont(font)
        self.Heart_Rate_LCD.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Heart_Rate_LCD.setStyleSheet("color: rgb(255, 255, 255);\n""")
        self.Heart_Rate_LCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Heart_Rate_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Heart_Rate_LCD.setSmallDecimalPoint(False)
        self.Heart_Rate_LCD.setDigitCount(4)
        self.Heart_Rate_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.Heart_Rate_LCD.setProperty("value", 0.0)
        self.Heart_Rate_LCD.setObjectName("Heart_Rate_LCD")
        self.gridLayout_5.addWidget(self.Heart_Rate_LCD, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(180, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setLineWidth(1)
        self.label_13.setScaledContents(True)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Assets/monitor.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Assets/thermometer (3).png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.Temperature_LCD = QtWidgets.QLCDNumber(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Temperature_LCD.sizePolicy().hasHeightForWidth())
        self.Temperature_LCD.setSizePolicy(sizePolicy)
        self.Temperature_LCD.setMinimumSize(QtCore.QSize(185, 150))
        self.Temperature_LCD.setStyleSheet("color: rgb(255, 255, 255);\n""")
        self.Temperature_LCD.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Temperature_LCD.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Temperature_LCD.setSmallDecimalPoint(False)
        self.Temperature_LCD.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.Temperature_LCD.setProperty("value", 0.0)
        self.Temperature_LCD.setObjectName("Temperature_LCD")
        self.gridLayout_3.addWidget(self.Temperature_LCD, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(1)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Assets/high.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.Solution_Volume_Progress_Bar.valueChanged['int'].connect(self.Solution_Volume_LCD.display) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Vital Signals Monitor"))
        self.label_11.setText(_translate("Form", "Vital Signals Monitor"))
        self.groupBox_3.setTitle(_translate("Form", "Solution Volume"))
        self.label_10.setText(_translate("Form", "ml"))
        self.groupBox_4.setTitle(_translate("Form", "Heart Rate"))
        self.label_13.setText(_translate("Form", "bpm"))
        self.groupBox.setTitle(_translate("Form", "Temperature"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    MAESTRO = AppManager.ApplicationManager(ui)
    Form.show()
    sys.exit(app.exec_())
